version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  back-end:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
        - 8000:8000
    depends_on:
        - db
  web-site:
    image: php:apache
    volumes:
      - ./client-php:/var/www/html
    ports:
        - 5000:80
    depends_on:
        - back-end